
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./local.env
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    env_file:
      - ./local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: